# This config file for Travis CI utilizes ros-industrial/industrial_ci package.		
# For more info for the package, see https://github.com/ros-industrial/industrial_ci/blob/master/README.rst		
sudo: required 		
dist: trusty 		
services:		
  - docker		
language: generic 		
compiler:		
  - gcc		
notifications:		
  email:
    on_success: never
    on_failue: never
  # slack: nishida-lab:Sczvu4bdpbngcXGeiZAEdHGx
env:		
  global:		
    - CATKIN_PARALLEL_TEST_JOBS=-p1		
    - ROS_PARALLEL_TEST_JOBS=-j`nproc`		
    - UPSTREAM_WORKSPACE=file
    - ROSINSTALL_FILENAME=.indigo_depends.rosinstall
    - BEFORE_SCRIPT='./.pre_process.sh'
    - TARGET_PKGS="motoman_mh5_support motoman_sda10f_support motoman_sia20d_moveit_config motoman motoman_msgs motoman_sia10d_support motoman_sia20d_support motoman_driver motoman_sda10f_moveit_config motoman_sia10f_support motoman_sia5d_support dhand_control dhand_description dhand_driver dhand_gazebo dhand_msgs dhand_ros_pkg motoman_demo_msgs motoman_moveit motoman_sia5_moveit_plugins motoman_description motoman_cable_removal  motoman_euclidean_cluster  motoman_point_cloud motoman_viz motoman_control motoman_gazebo motoman_rviz_plugins motoman_viz_msgs motoman_demo motoman_gripper motoman_sia5_moveit_config"
  matrix:		
    - ROS_DISTRO="indigo"  ROS_REPOSITORY_PATH=http://packages.ros.org/ros/ubuntu 
install:		
  - git clone -b add-source https://github.com/MoriKen254/industrial_ci.git .ci_config
script:		
  - source .ci_config/travis.sh 
